version: '2.4'
networks:
  network-api-gateway:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          ip_range: 192.168.0.0/28

services:
  #db
  api-gateway-database-postgres:
    image:
      postgres:12.2
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=kong
    - POSTGRES_PASSWORD=kong
    - POSTGRES_DB=kong
    networks:
      network-api-gateway:
        ipv4_address: 192.168.0.81
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  #migration
  api-gateway-kong-migration-command:
    image:
      kong:alpine
    user: root
    command: "kong migrations bootstrap"
    environment:
      - KONG_DATABASE:postgres
      - KONG_PG_PASSWORD=kong
      - KONG_PG_USER=kong
      - KONG_PG_DATABASE=kong
      - KONG_PG_HOST=192.168.0.81
    depends_on:
      api-gateway-database-postgres:
        condition: service_healthy
    networks:
      network-api-gateway:
        ipv4_address: 192.168.0.82

  #api-gateway
  api-gateway-kong:
    image:
      kong:alpine
    user: root
    links: [api-gateway-database-postgres]
    environment:
    - KONG_DATABASE:postgres
    - KONG_PG_PASSWORD=kong
    - KONG_PG_USER=kong
    - KONG_PG_DATABASE=kong
    - KONG_PG_HOST=192.168.0.81
    - KONG_ADMIN_LISTEN:0.0.0.0:8001
    - KONG_ADMIN_LISTEN_SSL:0.0.0.0:8444
    depends_on:
      - "api-gateway-kong-migration-command"
      - "api-gateway-database-postgres"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      network-api-gateway:
        ipv4_address: 192.168.0.83
    restart: on-failure

  api-gateway-admin-konga:
    image: "pantsel/konga"
    user: root
    links: [api-gateway-database-postgres]
    environment:
      - DB_ADAPTER:postgres
      - DB_PASSWORD=kong
      - DB_USER=kong
      - DB_DATABASE=kong
      - DB_PG_SCHEMA=kong
      - DB_HOST=192.168.0.81
      - DB_PORT=5432
      - NODE_ENV=production
      - TOKEN_SECRET=
    depends_on:
      - "api-gateway-kong"
      - "api-gateway-kong-migration-command"
      - "api-gateway-database-postgres"
    ports:
      - "1337:1337"
    networks:
      network-api-gateway:
        ipv4_address: 192.168.0.84
    restart: on-failure